<a href="https://colab.research.google.com/github/surkutecode/testpub/blob/main/MLT_wk_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# X=np.zeros(3)
# data_matrix = np.random.rand(8, 2) # 8 data points, 2 features
# print(data_matrix)
data_matrix.shape
X=np.ndarray(shape=(8,2))
print(X[0])

[0.99931667 0.03939573]


In [36]:
X=np.array([[1,0],[2,0],[3,0],[-1,0],[-2,0],[-3,0],[2,-1],[-2,1]])
# print(X)
X_centred=X-np.mean(X,axis=0)
# print(X_centred) # in our case X and X_centred are same
X_T=np.transpose(X_centred)
# print(X_T)
C=(1/8)*np.matmul(X_T,X_centred) # covariance matrix
print(C)

[[ 1  0]
 [ 2  0]
 [ 3  0]
 [-1  0]
 [-2  0]
 [-3  0]
 [ 2 -1]
 [-2  1]]
[[ 1.  0.]
 [ 2.  0.]
 [ 3.  0.]
 [-1.  0.]
 [-2.  0.]
 [-3.  0.]
 [ 2. -1.]
 [-2.  1.]]
[[ 1.  2.  3. -1. -2. -3.  2. -2.]
 [ 0.  0.  0.  0.  0.  0. -1.  1.]]
[[ 4.5  -0.5 ]
 [-0.5   0.25]]


In [39]:
eigen_values,eigen_vectors=np.linalg.eig(C)
print(eigen_values)
print(eigen_vectors)
print(eigen_vectors[0])

[4.55803115 0.19196885]
[[ 0.99333206  0.1152884 ]
 [-0.1152884   0.99333206]]
[0.99333206 0.1152884 ]


In [58]:
# in the GA9 given eigen vector is different [-0.993, 0.115]
ev=np.array([-0.993,0.115])
ev_T=np.transpose(ev)
print(ev.shape,ev_T.shape)
print(X.shape,X_T.shape)
# M=np.matmul(X,ev)
M=np.matmul(ev_T,X_T)
print(M.shape, M)
# Print(M.square())
M2=M*np.transpose(M)
print(M2)
M2.sum()*(1/8)

(2,) (2,)
(8, 2) (2, 8)
(8,) [-0.993 -1.986 -2.979  0.993  1.986  2.979 -2.101  2.101]
[0.986049 3.944196 8.874441 0.986049 3.944196 8.874441 4.414201 4.414201]


np.float64(4.55472175)

In [71]:
x=np.array([2,5])
w=np.array([1,1])
xp=np.matmul(x,w)*w/pow(np.linalg.norm(w),2)
print("xp: ",xp)
print("norm of Xp: ",np.linalg.norm(xp))
print("vector norm of Xp: ",np.linalg.vector_norm(xp))
print(xp*np.transpose(xp))
print(xp*xp)
print(np.transpose(xp))
print(xp)
print(np.matmul(np.transpose(xp),xp))
print("norm of w : ", np.linalg.norm(w))


xp:  [3.5 3.5]
norm of Xp:  4.949747468305832
vector norm of Xp:  4.949747468305832
[12.25 12.25]
[12.25 12.25]
[3.5 3.5]
[3.5 3.5]
24.49999999999999
norm of w :  1.4142135623730951


In [79]:
residue=x-xp
print(residue)
print(np.linalg.norm(residue))
print(np.matmul(residue,np.transpose(residue)))
print(np.matmul(np.transpose(residue),residue))
print(np.shape(residue))
r=np.array([[-1.5,1.5]])
print("r matrix:= ",r, "shape of r:- ",np.shape(r))
r_T=np.transpose(r)
print(r_T)
print(np.matmul(r_T,r))
print(np.matmul(r,r_T))

[-1.5  1.5]
2.1213203435596424
4.5
4.5
(2,)
r matrix:=  [[-1.5  1.5]] shape of r:-  (1, 2)
[[-1.5]
 [ 1.5]]
[[ 2.25 -2.25]
 [-2.25  2.25]]
[[4.5]]
